baseURL: "https://vitorhibeiro.github.io/vitorhribeiro.github.io/" 
title: VÃ­tor Hugo Ribeiro
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Publications
          url: papers/
          weight: 2
        - name: Education
          url: education/
          weight: 3
        - name: Data
          url: data/
          weight: 4

params:
    description: "This website hosts VÃ­tor's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: VÃ­tor Hugo Ribeiro
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","education"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: VÃ­tor Hugo Ribeiro
          subtitle: "PhD Student | Physics | Complex Systems | Complex Networks | Science of Science" 
          imageUrl: "profile.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: papers/
            - name: Education
              url: education/
            - name: Data 
              url: data/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
    #    - name: CV
    #      url: cv.pdf
        - name: Email
          url: mailto:vitorhibeiro@gmail.com
    #    - name: Zoom
    #      url: https://www.zoom.us/my/igelfeld
    #    - name: Location
    #      url: location/
    #    - name: Office Hours
    #      url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: Linkedin
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/pmichaillat
    #    - name: Substack
    #      url: https://pmichaillat.substack.com
    #    - name: YouTube
    #      url: https://www.youtube.com/@pmichaillat
    #    - name: Twitter
    #      url: https://x.com/pmichaillat
    #    - name: Bluesky
    #      url: https://bsky.app/profile/pmichaillat.bsky.social

---

    ðŸ’» I am a researcher-in-training with a passion for Science and Technology.

    I am currently a PhD student at the Physics Department of MaringÃ¡ State University (UEM) and a member of the ComplexLab research group. My research is in the field of Complex Systems, where I apply Complex Network theory to investigate the dynamics of 'Science of Science'.

---

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "V. H. Ribeiro"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
